### ISSUE TITLE
test_server.py

### ISSUE THREAD

**Issue by ps-star** [Dmmm1997/FSRA#10]
We use the scale: 1
-------test-----------
Traceback (most recent call last):
  File "test_server.py", line 200, in <module>
    model = load_network( opt)
  File "E:\浏览器下载\FSRA-master\FSRA-master\checkpoints\FSRA\tool\utils_server.py", line 114, in load_network
    model = two_view_net(opt.nclasses, block=opt.block)
TypeError: __init__() missing 1 required positional argument: 'class_num'

**Comment by walkeeet** [comment]
请问最后怎么解决的
