### ISSUE TITLE
I have a question about the missing file 'net_119.pth'

### ISSUE THREAD

**Issue by 8acemak1rkey** [Dmmm1997/FSRA#11]
when I run the code with the command 
bash train_test_local.sh
in the test section  there is an error,here are the detials

===========building transformer===========
using Transformer_type: vit_small_patch16_224_FSRA as a backbone
Load the model from net_119.pth
Traceback (most recent call last):
  File "test_server.py", line 200, in <module>
    model = load_network(opt)
  File "/home/qhc/FSRA-master/checkpoints/FSRA/tool/utils_server.py", line 119, in load_network
    model.load_state_dict(torch.load(save_filename))
  File "/home/qhc/anaconda3/envs/FSRA/lib/python3.7/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/qhc/anaconda3/envs/FSRA/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/qhc/anaconda3/envs/FSRA/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'net_119.pth'

And I have another question ,is there a file named 'opts.yaml'
I can't find it ,could you please help me ?
Thanks! Looking forward to your reply!

**Comment by 0121910870533** [comment]
I have the same problem as you. Have you solved it yet?
