### ISSUE TITLE
I have a question to consult with you

### ISSUE THREAD

**Issue by andynnnnn** [Dmmm1997/FSRA#9]
D:\Anaconda\envs\Grounding-Dino\python.exe D:/Github/FSRA-master/FSRA-master/checkpoints/test/test_server.py
This is not an error. If you want to use low precision, i.e., fp16, please install the apex with cuda support (https://github.com/NVIDIA/apex) and update pytorch to 1.0
We use the scale: 1
Traceback (most recent call last):
  File "D:/Github/FSRA-master/FSRA-master/checkpoints/test/test_server.py", line 200, in <module>
    model = load_network( opt)
  File "D:\Github\FSRA-master\FSRA-master\checkpoints\test\tool\utils_server.py", line 117, in load_network
    model = two_view_net(opt.nclasses, block=opt.block)
TypeError: __init__() missing 1 required positional argument: 'class_num'
-------test-----------

May I ask if the 'includes' and' class_num 'parameters in the code are different? Still expressing the same parameter？

**Comment by ps-star** [comment]
model = two_view_net(opt,opt.nclasses, block=opt.block)
